name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '💪 Enhancement'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '🔧 Refactoring'
    label: 'refactor'
  - title: '📖 Documentation'
    label: 'documentation'
  - title: '⛓️ Dependency update'
    label: 'dependencies'

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: enhancement
    title:
      - '/^:tada: .+/'
  - label: major
    title:
      - '/^:tada: .+/'
  - label: feature
    title:
      - '/^:sparkles: .+/'
  - label: minor
    title:
      - '/^:sparkles: .+/'
      - '/^:+1: .+/'
  - label: bug
    title:
      - '/^:bug: .+/'
  - label: patch
    title:
      - '/^:bug: .+/'
  - label: chore
    title:
      - '/^:wrench: .+/'
  - label: dependencies
    title:
      - '/^:up: .+/'
  - label: refactor
    title:
      - '/^:recycle: .+/'
  - label: documentation
    title:
      - '/^:books: .+/'
    files:
      - '*.md'
