-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.news
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    title character varying(128) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    content text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    published_at timestamp with time zone,
    eyecatch_id uuid,
    CONSTRAINT news_pkey PRIMARY KEY (id),
    CONSTRAINT news_eyecatch_id_fkey FOREIGN KEY (eyecatch_id)
        REFERENCES public.eyecatches (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.news
    OWNER to postgres;

ALTER TABLE IF EXISTS public.news
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.news TO anon;

GRANT ALL ON TABLE public.news TO authenticated;

GRANT ALL ON TABLE public.news TO postgres;

GRANT ALL ON TABLE public.news TO service_role;
CREATE POLICY "Enable read access for all users"
    ON public.news
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
