-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: supporter_rank
-- DROP TYPE IF EXISTS public.supporter_rank;
CREATE TYPE public.supporter_rank AS ENUM
    ('king', 'queen', 'jack', 'joker');

ALTER TYPE public.supporter_rank
    OWNER TO postgres;

-- Type: supporters
CREATE TABLE IF NOT EXISTS public.supporters
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    rank supporter_rank NOT NULL,
    url character varying(128) COLLATE pg_catalog."default",
    icon_image_url character varying(1024) COLLATE pg_catalog."default",
    CONSTRAINT supporters_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.supporters
    OWNER to postgres;

ALTER TABLE IF EXISTS public.supporters
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.supporters TO anon;

GRANT ALL ON TABLE public.supporters TO authenticated;

GRANT ALL ON TABLE public.supporters TO postgres;

GRANT ALL ON TABLE public.supporters TO service_role;
CREATE POLICY "Enable read access for all users"
    ON public.supporters
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
