-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: business_sponsor_rank
-- DROP TYPE IF EXISTS public.business_sponsor_rank;
CREATE TYPE public.business_sponsor_rank AS ENUM
    ('main', 'platinum', 'gold', 'silver', 'bronze', 'partner');

ALTER TYPE public.business_sponsor_rank
    OWNER TO postgres;

-- Table: business_sponsors
CREATE TABLE IF NOT EXISTS public.business_sponsors
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
                             name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    rank business_sponsor_rank NOT NULL,
    url character varying(128) COLLATE pg_catalog."default" NOT NULL,
    logo_image_url character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    sort bigint NOT NULL DEFAULT '100'::bigint,
    CONSTRAINT business_sponsors_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.business_sponsors
    OWNER to postgres;

ALTER TABLE IF EXISTS public.business_sponsors
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.business_sponsors TO anon;

GRANT ALL ON TABLE public.business_sponsors TO authenticated;

GRANT ALL ON TABLE public.business_sponsors TO postgres;

GRANT ALL ON TABLE public.business_sponsors TO service_role;
CREATE POLICY "Enable read access for all users"
    ON public.business_sponsors
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
