-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.eyecatches
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    url character varying(512) COLLATE pg_catalog."default" NOT NULL DEFAULT NULL::character varying,
    alt character varying COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    width smallint NOT NULL,
    height smallint NOT NULL,
    CONSTRAINT eyecatches_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eyecatches
    OWNER to postgres;

ALTER TABLE IF EXISTS public.eyecatches
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.eyecatches TO anon;

GRANT ALL ON TABLE public.eyecatches TO authenticated;

GRANT ALL ON TABLE public.eyecatches TO postgres;

GRANT ALL ON TABLE public.eyecatches TO service_role;
CREATE POLICY "Enable read access for all users"
    ON public.eyecatches
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
